# Generated by Django 3.0.2 on 2020-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='breed',
            field=models.CharField(default='feline', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
    ]
